### ISSUE TITLE
Can't access NA12878 files on ftp site

### ISSUE THREAD

**Issue by bmajoros** [Illumina/PlatinumGenomes#4]
It wants a password.

**Comment by blmoore** [comment]
The best way to get these files is from S3 either interactively via [this browser](https://illumina.github.io/PlatinumGenomes) or with `aws cli` as shown in the README. The legacy FTP should still work but might need an empty string as a password, e.g. `ftp://platgene_ro:''@ussd-ftp.illumina.com`
