### ISSUE TITLE
hg38 reference genome for

### ISSUE THREAD

**Issue by ksw9** [Illumina/PlatinumGenomes#5]
Hi, 
This is a great resource - I'm wondering which specific human reference genome you used for generating the sequence data NA12877_S1.bam and truth set pg2017/hg38/small_variants/NA12877/NA12877.vcf.gz so that we can get the appropriate ref genome to make best use of these tools? 

Thank you!

The VCF file lists the genome here but I'm wondering which publicly available version this is.
/illumina/sync/igenomes/Homo_sapiens/NCBI/GRCh38Decoy/Sequence/WholeGenomeFasta/genome.fa

**Comment by blmoore** [comment]
It's available through illumina's igenomes: http://emea.support.illumina.com/sequencing/sequencing_software/igenome.html

There's also this quite good (unofficial) resource: https://ewels.github.io/AWS-iGenomes/

**Comment by ksw9** [comment]
Got it, thank you!
